"""add_inference_snapshots_table

Revision ID: 1c63318e438c
Revises: 20260213_090000_0020
Create Date: 2026-02-13 18:23:16.080823+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c63318e438c'
down_revision: Union[str, None] = '20260213_090000_0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('pass_probability', sa.Float(), nullable=False),
    sa.Column('probability_source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('cognitive_stability', sa.Float(), nullable=False),
    sa.Column('retention_score', sa.Float(), nullable=False),
    sa.Column('drift_state', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('inference_latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_snapshots_attempt_id'), 'inference_snapshots', ['attempt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inference_snapshots_attempt_id'), table_name='inference_snapshots')
    op.drop_table('inference_snapshots')
    # ### end Alembic commands ###

